In [1]:
import os
import pandas as pd
import numpy as np
import ants
from matplotlib import pyplot as plt

In [2]:
def get_roi_data(im_fn,roi_fn):
    roi = ants.image_read(roi_fn)
    im = ants.image_read(im_fn)

    roi_data = im.numpy()[roi.numpy()==1].mean()
    return roi_data


In [3]:
indir = '../Data/StudyForrest/fmriprep/'
subs = [s for s in os.listdir(indir) if all((s.startswith('sub'),not s.endswith('.html')))]
subs.sort()
print(len(subs))


14


In [4]:
ofdir_root = '../Data/StudyForrest/ensembles_last_CVAE'
analysis_name = 'refactored-forrest-v3'
analysis_name = 'refac-baseline-forrest-v1'
analysis_name = 'refac-baseline-TC-forrest-v1'
analysis_name = 'refac-baseline-forrest-beta-1e-5'
analysis_name = 'DeepCor-forrest-v4-beta-1e-5'
ofdir = os.path.join(ofdir_root,analysis_name)

In [5]:
fn_temp = 'contrast_face_{s}_R{r}_deepcor.nii.gz'

In [20]:
rvec=[1,2,3,4]

In [21]:
svec = np.arange(len(subs))
#svec = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13]

In [22]:
roi_fn_temp = '../Data/StudyForrest/ROIs/rFFA_final_mask_{sub}_bin.nii.gz'
res = np.zeros((len(rvec),len(subs),3))
kinds = ['preproc','compcor','deepcor']
for s in svec:
    for r in rvec:
        for k in range(3):
            kind = kinds[k]
            im_fn = os.path.join(ofdir,'contrast_face_{s}_R{r}_{kind}.nii.gz'.format(s=s,r=r,kind=kind))
            roi_fn = roi_fn_temp.format(sub=subs[s])
            res[r-1,s,k] = get_roi_data(im_fn,roi_fn)
np.save(f'../Data/betas_forrest_face_{analysis_name}.npy',res)

In [23]:
roi_fn_temp = '../Data/StudyForrest/ROIs/rFFA_final_mask_{sub}_bin.nii.gz'
res = np.zeros((len(rvec),len(subs),3))
kinds = ['preproc','compcor','deepcor']
for s in svec:
    for r in rvec:
        for k in range(3):
            kind = kinds[k]
            im_fn = os.path.join(ofdir,'corr2face_S{s}_R{r}_{kind}.nii.gz'.format(s=s,r=r,kind=kind))
            roi_fn = roi_fn_temp.format(sub=subs[s])
            res[r-1,s,k] = get_roi_data(im_fn,roi_fn)
np.save(f'../Data/corr2face_forrest_{analysis_name}.npy',res)

In [24]:
roi_fn_temp = '../Data/StudyForrest/ROIs/rPPA_final_mask_{sub}_bin.nii.gz'
res = np.zeros((len(rvec),len(subs),3))
kinds = ['preproc','compcor','deepcor']
for s in svec:
    for r in rvec:
        for k in range(3):
            kind = kinds[k]
            im_fn = os.path.join(ofdir,'corr2place_S{s}_R{r}_{kind}.nii.gz'.format(s=s,r=r,kind=kind))
            roi_fn = roi_fn_temp.format(sub=subs[s])
            res[r-1,s,k] = get_roi_data(im_fn,roi_fn)
            
np.save(f'../Data/corr2place_forrest_{analysis_name}.npy',res)

In [25]:
roi_fn_temp = '../Data/StudyForrest/ROIs/rPPA_final_mask_{sub}_bin.nii.gz'
res = np.zeros((len(rvec),len(subs),3))
kinds = ['preproc','compcor','deepcor']
for s in svec:
    for r in rvec:
        for k in range(3):
            kind = kinds[k]
            im_fn = os.path.join(ofdir,'contrast_place_S{s}_R{r}_{kind}.nii.gz'.format(s=s,r=r,kind=kind))
            roi_fn = roi_fn_temp.format(sub=subs[s])
            res[r-1,s,k] = get_roi_data(im_fn,roi_fn)
            
np.save(f'../Data/betas_forrest_place_{analysis_name}.npy',res)

In [26]:
mot = np.zeros((len(rvec),len(subs)))
for s in svec:
    for r in rvec:
        sub = subs[s]
        conf_fn = os.path.join(indir,f'{sub}/ses-localizer/func/{sub}_ses-localizer_task-objectcategories_run-{r}_bold_confounds.tsv')
        df = pd.read_csv(conf_fn,delimiter='\t')
        fd = df['FramewiseDisplacement'].values[1::]
        mot[r-1,s]=fd.mean()

np.save('../Data/mot_forrest.npy',mot)

In [27]:
# analysis_name = 'refactored-forrest-v3'
# face_beta1 = np.load(f'../Data/betas_forrest_face_{analysis_name}.npy')
# analysis_name = 'refac-baseline-forrest-v1'
# face_beta2 = np.load(f'../Data/betas_forrest_face_{analysis_name}.npy')
# analysis_name = 'refac-baseline-TC-forrest-v1'
# face_beta3 = np.load(f'../Data/betas_forrest_face_{analysis_name}.npy')

In [28]:
# face_beta1.mean(axis=0).mean(axis=0).round(2)

In [29]:
# face_beta2.mean(axis=0).mean(axis=0).round(2)

In [30]:
# face_beta3.mean(axis=0).mean(axis=0).round(2)

In [31]:
import numpy as np

In [32]:
#aname='refac-baseline-forrest-v1'
#aname='refac-baseline-forrest-beta-1e-5'
aname='DeepCor-forrest-v4-beta-1e-5'

#aname = 'refactored-forrest-v3'
fn_face = f'../Data/corr2face_forrest_{aname}.npy'
fn_place = f'../Data/corr2place_forrest_{aname}.npy'

a = np.load(fn_face)
print(a.mean(axis=0).mean(axis=0).round(2))

a = np.load(fn_place)
print(a.mean(axis=0).mean(axis=0).round(2))

[0.14 0.16 0.22]
[0.23 0.25 0.37]


In [33]:
#aname='refac-baseline-forrest-v1'
#aname='refac-baseline-forrest-beta-1e-5'
#aname='DeepCor-forrest-v4-beta-1e-5'
#aname = 'refactored-forrest-v3'

fn_face = f'../Data/betas_forrest_face_{aname}.npy'
fn_place = f'../Data/betas_forrest_place_{aname}.npy'

a = np.load(fn_face)
print(a.mean(axis=0).mean(axis=0).round(2))

a = np.load(fn_place)
print(a.mean(axis=0).mean(axis=0).round(2))

[1.79 1.93 2.36]
[2.12 2.3  3.5 ]
